pipeline {
    agent any

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages {
        stage('Checkout') {
            steps {
                dir('test-go-webapp') {
                    git branch: 'main', url: 'https://github.com/MultipleCoffee/cicd-practice.git'
                }
            }
        }

        stage('Build') {
            steps {
                dir('test-go-webapp') {
                    sh '''
                        mkdir -p build
                        go build -o build/test-go-webapp main.go
                    '''
                }
            }
        }
        /*
        stage('Test') {
            steps {
                dir('test-go-webapp') {
                    sh 'go test ./...'
                }
            }
        }
        */

        stage('Prepare Artifact') {
            steps {
                dir('test-go-webapp') {
                    sh 'cp -r templates static build/'
                }
            }
        }

        stage('Deploy & Run') {
            steps {
                withCredentials([
                    string(credentialsId: 'target_ip', variable: 'TARGET_IP'),
                    string(credentialsId: 'test_goapp_port', variable: 'PORT'),
                    string(credentialsId: 'test_goapp_title', variable: 'APP_TITLE'),
                    string(credentialsId: 'ssh_port', variable: 'SSH_PORT'),
                    string(credentialsId: 'target_user', variable: 'TARGET_USER'),
                    usernamePassword(credentialsId: 'vm1_ssh_login', usernameVariable: 'SSH_USER', passwordVariable: 'SSH_PASS')
                ]) {
                    sh '''
                        # systemctl stop（sudoパスワード不要にしておくこと）
                        sshpass -p "$SSH_PASS" ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$TARGET_IP \
                            "sudo /bin/systemctl stop test-go-webapp.service || true"
                    
                        # バイナリを含むアーティファクト転送（停止後なのでText file busyにならない）
                        sshpass -p "$SSH_PASS" scp -P $SSH_PORT -o StrictHostKeyChecking=no -r test-go-webapp/build/* \
                            $SSH_USER@$TARGET_IP:/home/$TARGET_USER/test-go-webapp/
                    
                        # systemctl start（再起動）
                        sshpass -p "$SSH_PASS" ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$TARGET_IP \
                            "sudo /bin/systemctl start test-go-webapp.service"
                    '''
                }
            }
        }
    }
}

